# Site settings
title:       zdf's blog
email:       615328619@qq.com 
author:      Zhao Dongfang
description: "A simple, beautiful theme for Jekyll that emphasizes content rather than aesthetic fluff."
baseurl:     ""
url:         "http://zdf615328619.github.io/"

# Google analytics
google_analytics:

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: true
github_username: zdf615328619
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     5
sass:
  compressed: true

# lsi setting (let related_post has more quality)
lsi: 		false
